version: '3'
services:
  #コンテナ名 nginx, php, db, phpmyadmin
  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    #ここでは、自身のパソコンにあるファイルと
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./www/html:/var/www/html
    #このnginxがphpのコンテナと繋がっているということを、示している。
    depends_on:
      - php

  php:
    build: ./php
    volumes:
      - ./www/html:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:latest
    ports:
      - 13306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./initdb.d/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      
      
    environment:
      MYSQL_DATABASE: webapp
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: secret
    stdin_open: true
    privileged: true
      
  #depends_onより、dbからnginxの順にコンテナが構築される。

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin:latest
  #   ports:
  #     - 8888:80
  #   depends_on:
  #     - db